# Site settings
title:       'Ada Resouce Hub'
email:
description: 'Community Site'
url:         'https://jquorning.github.io'
baseurl:
twitter_username:
github_username:  jquorning

# Build settings
markdown: kramdown
permalink: pretty
